module.exports.keyedHash = {
  "milk"       : "5.50",
  "cheese"     : "6.20",
  "beer"       : "13.80",
  "wine"       : "23.25",
  "bread"      : "4.00",
  "apples"     : "2.00",
  "eggs"       : "2.99",
  "butter"     : "3.87",
  "ham"        : "8.35",
  "fruit"      : "4.75",
  "bananas"    : "2.50",
  "mayonnaise" : "4.90",
  "cereal"     : "6.10",
  "coffee"     : "9.50",
  "pasta"      : "3.20",
  "chicken"    : "6.82",
  "popcorn"    : "5.00",
  "fish"       : "9.20",
  "sugar"      : "2.00",
  "vegetables" : "5.50"
}
module.exports.list = [
  "milk",
  "cheese",
  "beer",
  "wine",
  "bread",
  "apples",
  "eggs",
  "butter",
  "ham",
  "fruit",
  "bananas",
  "mayonnaise",
  "cereal",
  "coffee",
  "pasta",
  "chicken",
  "popcorn",
  "fish",
  "sugar",
  "vegetables"
]
